version: '3.9'

services:
  dev-db:
    image: postgres:13
    restart: always
    container_name: dev-db
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - devdata:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    restart: always
    container_name: test-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    volumes:
      - testdata:/var/lib/postgresql/data
volumes:
  devdata:
  testdata:
